server:
  port: 8888
  servlet:
    context-path: /shop
spring:
  datasource:
    username: root
    password: Ll03001360
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 如果指定 schema 包含了其他表,但没有 flyway schema history 表的话, 在执行 flyway migrate 命令之前, 必须先执行 flyway baseline 命令.
  # 设置 spring.flyway.baseline-on-migrate 为 true 后, flyway 将在需要 baseline 的时候, 自动执行一次 baseline.
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration
mybatis:
  configuration:
    map-underscore-to-camel-case: true

