server:
  port: 8888
  servlet:
    context-path: /shop
spring:
  datasource:
    username: root
    password: ll03001360
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
